#!/bin/bash
PERSON1=lakshmi
PERSON2=kamala

echo "$PERSON1::  Hi ${PERSON2}, How are you?"
echo "${PERSON2}:: Hellow $PERSON1,i am fine.how are you doing?"
echo "$PERSON1:: I am good ${PERSON2}.what's going on?"
echo "${PERSON2}::I started learning shell scripting $PERSON1"
